'use client';
import {useEffect,useState} from 'react';
import {Sheet,SheetTrigger,SheetContent,SheetTitle,SheetClose} from '@/components/ui/sheet';
import {ArrowUpRight,Menu,X,MessageCircle} from 'lucide-react';
import {links} from './navigation';
export function Brand({light=false}:{light?:boolean}){return <a className="brand brand-mark" href="/" aria-label="AD Consulting, inicio"><img src={light?'/images/ad-consulting-logo-light.png':'/images/ad-consulting-logo-dark.png'} alt="AD Consulting"/></a>}
export function Header({active='Inicio'}:{active?:string}){return <header className="header"><Brand/><nav aria-label="Navegación principal">{links.map(([name,url])=><a key={url} href={url} aria-current={active===name?'page':undefined}>{name}</a>)}<a href="https://aulavirtual.adcapacitaciones.cl/login/index.php" target="_blank" rel="noreferrer">Aula Virtual</a><a href="https://adconsulting.trabajando.cl/" target="_blank" rel="noreferrer">Ofertas de Trabajo</a></nav><a className="contact-link" href="#contacto">Hablemos <ArrowUpRight size={17}/></a><Sheet><SheetTrigger className="menu-button" aria-label="Abrir menú"><Menu size={24}/></SheetTrigger><SheetContent className="menu-panel" side="right" showCloseButton={false}><div className="menu-top"><SheetTitle className="menu-title">AD Consulting</SheetTitle><SheetClose aria-label="Cerrar menú" className="menu-close"><X size={28}/></SheetClose></div><div className="menu-links">{links.map(([name,url],i)=><a style={{animationDelay:`${i*50}ms`}} href={url} key={url}><small>0{i+1}</small>{name}<ArrowUpRight/></a>)}</div><div className="menu-secondary"><a href="https://aulavirtual.adcapacitaciones.cl/login/index.php">Aula Virtual</a><a href="https://adconsulting.trabajando.cl/">Ofertas de Trabajo</a><a href="mailto:contacto@adconsulting.cl">contacto@adconsulting.cl</a></div></SheetContent></Sheet></header>}
export function Motion(){useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);return null}
export function Contact(){const[ready,setReady]=useState(false);return <section className="section contact" id="contacto"><div className="reveal"><p className="eyebrow">CONECTEMOS</p><h2>Hablemos<span className="dot">.</span></h2><p>Déjanos tus datos y te contactaremos lo antes posible</p><a className="text-link" href="mailto:contacto@adconsulting.cl">contacto@adconsulting.cl <ArrowUpRight size={20}/></a></div><form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);const body=['Nombre','Empresa','Email','Celular'].map(k=>`${k}: ${d.get(k)}`).join('\n');window.location.href=`mailto:contacto@adconsulting.cl?subject=${encodeURIComponent('Contacto desde AD Consulting')}&body=${encodeURIComponent(body)}`;setReady(true)}}><div className="form-grid">{[['Nombre','text','name'],['Empresa','text','organization'],['Email','email','email'],['Celular','tel','tel']].map(([label,type,auto])=><label key={label}>{label}<input name={label} type={type} autoComplete={auto} placeholder={`Ingresa tu ${label.toLowerCase()}`} required maxLength={150}/></label>)}</div><div className="form-bottom"><p>Al continuar, se abrirá tu aplicación de correo para enviar tus datos.</p><button type="submit" className="button">¡Conectemos! <ArrowUpRight size={22}/></button></div>{ready&&<p className="form-status" role="status">Tu mensaje está preparado en tu aplicación de correo. Envíalo para completar el contacto.</p>}</form></section>}
