import source from '@/content/source.json';
import {Header,Brand,Motion,Contact} from './interactive';
import {links} from './navigation';
import {ArrowUpRight,ArrowDown} from 'lucide-react';
import type {ReactNode} from 'react';
const photos = [
  {file:'adconsulting-web11.jpeg',alt:'Conversación de asesoría profesional en una oficina',focus:'50% 45%',mobile:'35% 45%'},
  {file:'adconsulting-web7.jpeg',alt:'Equipo participando en una sesión de trabajo colaborativo',focus:'50% 40%',mobile:'63% 40%'},
  {file:'adconsulting-web2.jpeg',alt:'Revisión de currículums durante un proceso de selección',focus:'65% 45%',mobile:'68% 45%'},
  {file:'adconsulting-web8.jpeg',alt:'Profesionales conversando sobre una trayectoria laboral',focus:'50% 40%',mobile:'32% 40%'},
  {file:'adconsulting-web9.jpeg',alt:'Profesional con una carpeta en un entorno empresarial',focus:'50% 35%',mobile:'50% 35%'},
  {file:'adconsulting-web10.jpeg',alt:'Sesión de capacitación presencial con un grupo de profesionales',focus:'58% 40%',mobile:'63% 40%'},
  {file:'adconsulting-web3.jpeg',alt:'Entrevista de selección con revisión de antecedentes',focus:'50% 45%',mobile:'64% 45%'},
  {file:'adconsulting-web6.jpeg',alt:'Conversación individual de acompañamiento y desarrollo',focus:'50% 40%',mobile:'35% 40%'},
  {file:'adconsulting-web5.jpeg',alt:'Sesión de orientación y acompañamiento profesional',focus:'48% 45%',mobile:'35% 45%'},
  {file:'adconsulting-web12.jpeg',alt:'Profesional participando en una sesión de formación a distancia',focus:'52% 45%',mobile:'40% 45%'},
  {file:'adconsulting-web14.jpeg',alt:'Mesa preparada para una reunión de asesoría',focus:'60% 55%',mobile:'70% 55%'},
];
const clientLogos = ['aco.9bb88454.webp','altos_valle.920bb7b9.webp','arauco.e142d465.webp','avicola_chequen.39b7b6b5.webp','biodiversa.24c5745c.webp','blumar.d36b0385.webp','clinica_andes.52b94335.webp','clinica_biobio.5640ab5d.webp','cmp.85632906.webp','corp_masonica.503ae9de.webp','cpc_biobio.1e1597e3.webp','dpc.bcbccdf2.webp','ds.1ac56f73.webp','eo.3afe284b.webp','estadio_espanol.3b05e6da.webp','grupo_avanza.d99b2b45.webp','isla_maquinarias.0d4de502.webp','itahue.c7ec7b65.webp','leon.6fe82453.webp','masonite.58973ced.webp','mnk.8c4e1ca2.webp','molycop.07b592f5.webp','mvc.9ce61772.webp','orizon.7c7badc9.webp','pinares.63214379.webp','puerto_coronel.0de52f08.webp','san_vicente.e850cae0.webp','sanatorio_aleman.067f550c.webp','santa_blanca.94159c9a.webp','setop.adfdef7e.webp','udd.b9000488.webp','uss.48e6c981.webp','ust.e50ce338.webp','valmar.92e8d890.webp'];
function photoStyle(index:number){return {'--photo-focus':photos[index].focus,'--photo-focus-mobile':photos[index].mobile} as import('react').CSSProperties}
export function Picture({index,alt,className=''}:{index:number,alt?:string,className?:string}){return <img src={'/images/'+photos[index].file} alt={alt ?? photos[index].alt} loading="lazy" className={`service-photo ${className}`} style={photoStyle(index)}/>}
export function Button({href,children}:{href:string,children:ReactNode}){return <a className="button" href={href}>{children}<ArrowUpRight size={22}/></a>}
export function Hero({title,description,label,image=0,cta,href='#contenido',compact=false}:{title:string,description?:string,label:string,image?:number,cta?:string,href?:string,compact?:boolean}){return <section className={`hero ${compact?'hero-inner':''}`}><img className="service-photo" style={photoStyle(image)} src={'/images/'+photos[image].file} alt={photos[image].alt} fetchPriority="high"/><div className="hero-content"><p className="eyebrow">{label}</p><h1>{title}</h1>{description&&<p className="hero-description">{description}</p>}{cta&&<Button href={href}>{cta}</Button>}</div><a className="hero-bottom" href="#contenido"><span>AD CONSULTING · PERSONAS Y ORGANIZACIONES</span><span>Desliza para descubrir <ArrowDown size={16}/></span></a></section>}
export function Footer({black=false,senior=false}:{black?:boolean,senior?:boolean}){return <footer className="footer"><div className="footer-statement"><h2>{senior?'Ninguna estrategia supera un equipo de trabajo bien elegido. El verdadero éxito de una Empresa se alcanza cuando reúne a las personas adecuadas para convertir sus desafíos y objetivos en resultados.':black?'Redefinimos la experiencia de impactar juntos.':<>El éxito en una empresa radica en <em>seleccionar y potenciar</em> a las personas adecuadas para cada desafío</>}</h2></div><div className="footer-links"><Brand/><div>{links.slice(1).map(([name,url])=><a href={url} key={url}>{name==='Nosotros'?'Nosotr@s':name}</a>)}</div><div><a href="https://aulavirtual.adcapacitaciones.cl/login/index.php">Aula Virtual ↗</a><a href="https://adconsulting.trabajando.cl/">Ofertas de Trabajo ↗</a><a href="https://www.instagram.com/adconsultingchile/">Instagram ↗</a><a href="https://www.linkedin.com/in/ariela-dymensztain-ad/">LinkedIn ↗</a></div></div><div className="footer-bottom"><p>AD Consulting | San Martín 553 of. 1004, Edificio Millenium II, Chile</p><div className="certifications">{source.home.images.slice(7).map(im=><img key={im.src} src={im.src} alt={im.alt} loading="lazy"/>)}</div></div></footer>}
export function Shell({active,children,contact=true,black=false}:{active:string,children:ReactNode,contact?:boolean,black?:boolean}){return <><a className="skip-link" href="#main">Saltar al contenido</a><Header active={active}/><main id="main" className={black?'black-page':''}>{children}{contact&&<Contact/>}{!contact&&<div className="simple-contact" id="contacto"><a className="text-link" href="mailto:contacto@adconsulting.cl">Contáctanos aquí <ArrowUpRight size={22}/></a></div>}</main><Footer black={black} senior={active==='AD+50'}/><Motion/></>}
const serviceIndices=[3,5,7,11,17];
const lossCards=[
  {title:'La empresa',summary:'Pierde productividad, conocimiento y continuidad.',items:['Rotación silenciosa y pérdidas operacionales.','Vacantes que el mercado joven no cubre.','Tensiones intergeneracionales sin gestión efectiva.']},
  {title:'El profesional +50',summary:'Pierde vigencia, ingresos y trayectoria.',items:['Sale del mercado formal hacia la informalidad y subempleo.','Desactualización digital e IA, nuevas habilidades de gestión y narrativa profesional vencida.','Ausencia de redes, invisibilidad profesional y pérdida de confianza.']},
  {title:'La sociedad',summary:'Pierde competitividad y sostenibilidad económica.',items:['Pérdida de competitividad y sostenibilidad económica.','Presión sobre pensiones y otras prestaciones sociales.','Impacto sobre la salud mental y vulnerabilidad psicosocial.']},
];
const comparisonCards=[
  {title:'Lo que las Empresas suelen pensar',items:['Son caros y producen lo mismo que jóvenes talentosos más baratos.','Están desactualizados y son adversos a los cambios.']},
  {title:'Lo que realmente está pasando',items:['Aumentos de costo por rotación, pérdidas operacionales y de continuidad.','Dificultades en el reclutamiento de fuera laboral joven.','Débil gestión de las relaciones intergeneracionales.']},
];
export function HomePage(){const d=source.home.text;return <Shell active="Inicio"><Hero title={d[1]} description="Más de 14 años de experiencia en procesos de Head Hunting, Reclutamiento, Selección de Talentos, Outplacement, Capacitación y Coaching Ejecutivo" label="AD CONSULTING" cta="Nuestros Servicios" href="/servicios/"/><section className="partners" aria-label="Nuestros partners"><p>Nuestros partners</p><div>{source.home.images.filter(im=>im.alt !== 'Codify' && im.alt !== 'Equipo AD Consulting').slice(0,5).map(im=><img key={im.src} src={im.src} alt={im.alt} loading="lazy"/>)}</div></section><section className="section impact" id="contenido"><div className="impact-heading reveal"><p className="eyebrow">AD CONSULTING</p><h2>¡Impactando en la productividad de <em>+100 empresas!</em></h2></div><div className="benefits-grid">{[11,13,15].map((n,i)=><article className="reveal" key={n}><span className="index">0{i+1}</span><h3>{d[n]}</h3><p>{d[n+1]}</p></article>)}</div></section><section className="split-feature"><div className="image-wrap"><Picture index={2}/></div><div className="feature-copy reveal"><p className="eyebrow">NUESTROS SERVICIOS</p><h2>Soluciones a tu medida</h2><div className="service-links">{serviceIndices.map((n,i)=><a key={n} href={`/servicios/#servicio-${i+1}`}>{source.servicios.text[n]}<ArrowUpRight/></a>)}</div></div></section><section className="client-logos" aria-label="Empresas impactadas"><h2><span>Empresas a las que hemos</span><strong>IMPACTADO</strong></h2><div className="client-marquee"><div className="client-track">{[0,1].map(copy=><div className="client-group" key={copy} aria-hidden={copy===1 ? true : undefined}>{clientLogos.map(file=><img key={file} src={`/images/client-${file}`} alt="Empresa cliente de AD Consulting" loading="lazy"/>)}</div>)}</div></div></section></Shell>}
export function AboutPage(){const d=source.nosotros;return <Shell active="Nosotros"><Hero title={d.text[1]} label="NOSOTR@S" image={1} compact/><section className="section about-intro reveal" id="contenido"><p className="eyebrow">AD CONSULTING</p><h2>{d.text[2]}</h2></section><section className="section team-section"><div className="section-heading"><h2>{d.text[3]}</h2><p>{d.text[4]}</p></div><div className="team-grid">{d.images.slice(0,11).map((im,i)=><article className="person reveal" key={im.src}><div className="person-image"><img src={im.src} alt={im.alt} loading="lazy"/></div><h3>{d.text[5+i*2]}</h3><p>{d.text[6+i*2]}</p></article>)}</div></section></Shell>}
export function ServicesPage(){const d=source.servicios;return <Shell active="Servicios"><Hero title={d.text[1]} description={d.text[2]} label="SERVICIOS" image={2} cta="Conoce nuestros servicios" compact/><div className="service-index" id="contenido">{serviceIndices.map((n,i)=><a href={`#servicio-${i+1}`} key={n}><span>0{i+1}</span>{d.text[n]}</a>)}</div>{serviceIndices.map((n,i)=><section className={`service-detail ${i%2?'reversed':''}`} key={n} id={`servicio-${i+1}`}><div className="image-wrap"><Picture index={[0,6,7,8,5][i]} alt={d.text[n]}/></div><div className="service-copy reveal"><p className="eyebrow">SERVICIOS / 0{i+1}</p><h2>{d.text[n]}</h2><p>{d.text[n+1]}</p>{i===3&&<><p>{d.text[13]}</p><p className="service-note">{d.text[14]}</p></>}{i===4&&<p>{d.text[19]}</p>}{i===2&&<a href="https://www.youtube.com/watch?v=XOzHQBbgBEM&ab_channel=ReddeRRHH" target="_blank" rel="noreferrer" className="text-link">Si quieres saber mas ve este video <ArrowUpRight size={20}/></a>}{i===3&&<a href="https://youtu.be/2a7JT4ILtOI" target="_blank" rel="noreferrer" className="text-link">Si quieres saber mas ve este video <ArrowUpRight size={20}/></a>}</div></section>)}<section className="section service-cert"><h2>{d.text[20]}</h2><div className="cert-row">{d.images.slice(8,12).map(im=><img key={im.src} src={im.src} alt={im.alt} loading="lazy"/>)}</div></section></Shell>}
export function NewsCards({limit=16}:{limit?:number}){const news=source.noticias.links.filter(([url])=>url.includes('revistanos.cl'));return <div className="news-grid">{news.slice(0,limit).map(([url,title],i)=><a href={url} target="_blank" rel="noreferrer" className="news-card reveal" key={url+i}><div className="news-image"><img src={source.noticias.images[i].src} alt={source.noticias.images[i].alt} loading="lazy"/></div><p className="eyebrow">AD CONSULTING · REVISTA NOS</p><h3>{title}</h3><span className="text-link">Leer noticia <ArrowUpRight size={20}/></span></a>)}</div>}
export function NewsPage(){return <Shell active="Noticias" contact={false}><Hero title="Noticias" label="AD CONSULTING" image={5} compact/><section className="section news-section" id="contenido"><NewsCards/></section></Shell>}
export function SeniorPage(){const d=source.ad50.text;return <Shell active="AD+50" contact={false}><Hero title="El futuro del trabajo se construye con experiencia" label="AD+50 · TALENTO SENIOR" image={3} cta="Ir a AD+50" href="https://ad50.adconsulting.cl"/><section className="section senior-intro" id="contenido"><div className="reveal"><p className="eyebrow">AD+50</p><h2>El talento ya no es el mismo y las empresas no están gestionando ese cambio</h2></div><div className="three-statements">{[8,11,14].map((n,i)=><div key={n}><span>0{i+1} ↓</span><h3>{d[n]} {d[n+1]}</h3></div>)}</div><div className="platform-link"><p>{d[16]}</p><a href="https://ad50.adconsulting.cl" className="text-link">{d[17]} <ArrowUpRight/></a></div></section><section className="split-feature"><div className="image-wrap"><Picture index={9}/></div><div className="feature-copy reveal"><p className="eyebrow">TALENTO SENIOR</p><h2>{d[18]}</h2><p>Un servicio de AD Consulting que instala una mirada estratégica sobre el talento senior, abordando integralmente el reclutamiento, el entrenamiento continuo, la actualización de competencias y la consultoría orientada a una equilibrada convivencia intergeneracional en las organizaciones.</p></div></section><section className="section"><p className="eyebrow">{d[22]}</p><h2 className="section-title reveal">Un fenómeno que se repite y que no es sobre bienestar</h2><p className="lead">Es perder productividad, continuidad operacional y acceso al talento crítico.</p><div className="loss-grid">{lossCards.map(card=><article className="reveal" key={card.title}><h3>{card.title}</h3><p>{card.summary}</p><ul>{card.items.map(item=><li key={item}>{item}</li>)}</ul></article>)}</div></section><section className="section approach"><p className="eyebrow">{d[42]}</p><h2 className="section-title reveal">{d[43]} <em>{d[44]}</em></h2><p className="lead">{d[45]}</p><div className="comparison">{comparisonCards.map((card,i)=><article key={card.title}><h3>{card.title}</h3><ul>{card.items.map(item=><li key={item}><span>{i?'↗':'—'}</span>{item}</li>)}</ul></article>)}</div></section><section className="section action-section"><p className="eyebrow">{d[56]}</p><h2 className="section-title">{d[57]} <em>{d[58]}</em></h2><p className="lead">{d[59]}</p><div className="action-lines">{[60,63,66,69,72].map(n=><article className="reveal" key={n}><span>{d[n]}</span><h3>{d[n+1]}</h3><p>{d[n+2]}</p></article>)}</div></section><section className="section senior-team"><p className="eyebrow">{d[75]}</p><h2>{d[76]}</h2><p className="lead">{d[77]}</p><div className="team-grid">{[78,81,84,87].map((n,i)=><article className="person reveal" key={n}><div className="person-image"><img src={source.ad50.images[6+i].src} alt={source.ad50.images[6+i].alt} loading="lazy"/></div><h3>{d[n]}</h3><p>{d[n+1]}</p><p>{d[n+2]}</p></article>)}</div></section></Shell>}
export function BlackPage(){const d=source.black;return <Shell active="ADblack" black contact={false}><Hero title={d.text[1]} label="AD BLACK" image={10} cta="Beneficios AD Black"/><section className="section black-intro" id="contenido"><p className="eyebrow">CÍRCULO AD BLACK</p><h2 className="reveal">{d.text[7]}</h2><div className="black-columns"><p>{d.text.slice(2,7).join(' ').replace(' ,',',')}</p><p>{d.text[8]}</p></div></section><section className="black-benefits"><div className="black-card-image"><img src={d.images[0].src} alt={d.images[0].alt} loading="lazy"/></div><div className="black-benefit-copy"><h2>{d.text[9]}</h2>{d.text.slice(10,15).filter(t=>!t.startsWith("Bono de Bienvenida AD Black")).map((t,i)=><article className="reveal" key={t}><span>0{i+1}</span><p>{t}</p></article>)}</div></section><section className="black-benefit-images section">{d.images.slice(1,3).map(im=><img key={im.src} src={im.src} alt={im.alt} loading="lazy"/>)}</section></Shell>}
